dist: xenial

language: scala

scala:
  - 2.11.12
  - 2.12.12
  - 2.13.4
  - 3.0.0-M2

jdk:
  - openjdk8

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" scallopJVM/test scallopJS/test scallopNative/test
